### ISSUE TITLE
Unify serialize:toMap and deserialize:fromMap

### ISSUE THREAD

**Issue by tejainece** [Jaguar-dart/jaguar_serializer#109]

**Comment by lejard-h** [comment]
Renaming maybe, but I don't think it is possible, `fromMap` and `toMap` are link to 1 class and convert a class to a Map or a Map to a class.

`serialize` and `deserialize` are on repository and help handling list of class or Map of class.

but `from` and `to` function on `repository` should not be visible

**Comment by lejard-h** [comment]
probably link to https://github.com/Jaguar-dart/jaguar_serializer/issues/108

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_serializer/pull/117/commits/fe65f9410ffe5d0fb798a51f10e29c67b5bd2e93
