### ISSUE TITLE
[perf] - wrong serializer instanciation

### ISSUE THREAD

**Issue by lejard-h** [Jaguar-dart/jaguar_serializer#130]
for exemple:

```dart
 Serializer  __serializer;
 Serializer get  _serializer => __serializer ?? new SomeSerializer();
```

it should be

```dart
Serializer get  _serializer => __serializer ??= new SomeSerializer();
```

**Comment by Kleak** [comment]
or 
```dart
final _interestPercentSerializer = new SomeSerializer();
```

**Comment by tejainece** [comment]
@lejard-h Good catch!

@Kleak This is done this way because of this bug: https://github.com/Jaguar-dart/jaguar_serializer/issues/114

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_serializer/pull/131/commits/5d56659596c69973b494f69626a3d3d08a05c3e3
