### ISSUE TITLE
SafeNum processor does not work

### ISSUE THREAD

**Issue by lejard-h** [Jaguar-dart/jaguar_serializer#152]
`JaguarCliException: FieldProcessor SafeNumProcessor processes deserializes num to dynamic. But field has type double.`

**Comment by tejainece** [comment]
Provide complete example, please.

Best case add a testcase.

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_serializer/commit/d4b72628398d21792073416aff7e90a29c2c32ed

Please reopen the issue if it is not fixed.

Thanks.
