### ISSUE TITLE
Add immutability capabilities

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_serializer#153]
being able to serialize deserialize immutable models is important in my opinion :) 
From what I know it's not possible yet

**Comment by tejainece** [comment]
Do you mean like this? https://github.com/Jaguar-dart/jaguar_serializer/wiki/Immutable-fields

**Comment by tejainece** [comment]
Here are some examples:

https://github.com/Jaguar-dart/jaguar_serializer/tree/master/jaguar_serializer_cli/test/models/immutable
https://github.com/Jaguar-dart/jaguar_serializer/blob/master/jaguar_serializer_cli/test/serializer/fromMap/immutable_test.dart

**Comment by jaumard** [comment]
Sorry about that I miss it ^^
