### ISSUE TITLE
With version 2.2.1 and the latest flutter/dart I get hanging 100% CPU dart process.

### ISSUE THREAD

**Issue by mjaffa-figure** [Jaguar-dart/jaguar_serializer#157]
When I run: "flutter packages pub run build_runner build --delete-conflicting-outputs"

The dart process cpu % goes to 100% and just hangs there forever. Here is the output:

flutter packages pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 333ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[WARNING] Throwing away cached asset graph due to version mismatch.
[INFO] Reading cached asset graph completed, took 37ms

[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 439ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Deleting 5 declared outputs which already existed on disk.
[INFO] Checking for unexpected pre-existing outputs. completed, took 6ms

[INFO] Running build...
[INFO] 1.0s elapsed, 1/17 actions completed.
[INFO] 2.1s elapsed, 1/17 actions completed.
[INFO] 3.1s elapsed, 1/17 actions completed.
[INFO] 10.6s elapsed, 5/17 actions completed.
[INFO] 11.8s elapsed, 16/17 actions completed.
[INFO] 12.9s elapsed, 21/21 actions completed.

And just never returns.

**Comment by tejainece** [comment]
Hi, What happened here? Did you manage to fix it?

**Comment by mjaffa-figure** [comment]
On one of my class serializers I didn't have a dependent serializer defined so it was hanging.

**Comment by tejainece** [comment]
ok
