### ISSUE TITLE
not compatible with angular 5.3.0

### ISSUE THREAD

**Issue by lejard-h** [Jaguar-dart/jaguar_serializer#179]
The cli is not compatible with the last version of Angular

Probably due to the analyzer

angular `5.3.0` need analyzer `0.35.0`.

Note that the 6.0.0-alpha will need the `0.36.0` version

**Comment by tejainece** [comment]
`jaguar_serializer_cli` version `2.2.6` supports analyzer 0.36.0.

For 0.35.0 please use override dependencies.

**Comment by tejainece** [comment]
Please reopen the issue if there are still issues. Also let me know if it works.
