### ISSUE TITLE
Wrong typecast String to double/int when deserializing - typecast error

### ISSUE THREAD

**Issue by dmitryivan** [Jaguar-dart/jaguar_serializer#181]
If json has String value and model need Int/double - it tries:
"map['myValueName'] as double"
 while it's not working anymore in Dart and should be:
"double.parse('myValueName')"
The result is exception:  'type 'String' is not a subtype of type 'double' in type cast'

**Comment by tejainece** [comment]
Jaguar does not automatically cast string to double. I think what you are looking for is a FieldProcessor.

**Comment by dmitryivan** [comment]
Well, in fact it doesn't, but it tries - as can be seen in autogenerated .jser files
I think the cast issue can be fixed as stated above

**Comment by escamoteur** [comment]
Just hit the same problem because the received JSON contains whole number without a decimal point. double.parse might be the better solution. I don't want to use a field processor for every double member

**Comment by tejainece** [comment]
double is a number. It is not a string. `double.tryParse` converts string to double.

Why should double fields automatically convert from strings? This is a good usecase for FieldProcessor.

**Comment by tejainece** [comment]
@dmitryivan Jaguar already has a string to double FieldProcessor: https://pub.dev/documentation/jaguar_serializer/latest/jaguar_serializer/DoubleToStringProcessor-class.html

**Comment by tejainece** [comment]
@escamoteur For your case, we have to use `num.toDouble` instead. I will fix that.

**Comment by escamoteur** [comment]
I was just finishing my PR :-)

**Comment by jaumard** [comment]
Does this one can be closed now @escamoteur ?

**Comment by escamoteur** [comment]
I think so :-) thanks for merging and I hope a new version get's pushed soon.

**Comment by jaumard** [comment]
Sure I trying to publish it soon !
