### ISSUE TITLE
Serialize when a nested custom object is null crash 

### ISSUE THREAD

**Issue by Kleak** [Jaguar-dart/jaguar_serializer#23]

**Comment by tejainece** [comment]
https://github.com/Jaguar-dart/jaguar_serializer/pull/24/commits/da0aa6d4e381472be8672b860cdc4a927887c9f0 implements testcase to reproduce this issue

**Comment by tejainece** [comment]
Fixed in https://github.com/Jaguar-dart/jaguar_serializer/pull/24/commits/c2b5a24ecbf5a58c2d6100e4147471c5c04b10de
