### ISSUE TITLE
When `asAndFrom` is not specified in `EnDecodeField`, null is assumed as name of the field

### ISSUE THREAD

**Issue by tejainece** [Jaguar-dart/jaguar_serializer#41]
When `asAndFrom` is not specified in `EnDecodeField`, null is assumed as name of the field

May affect `EncodeField` and `DecodeField` too.

**Comment by lejard-h** [comment]
what is the state of this ?

**Comment by tejainece** [comment]
Haven't tested it in a while. Will test it again later.

**Comment by tejainece** [comment]
Write test case for this
