### ISSUE TITLE
Introduce @RawMap and @RawList

### ISSUE THREAD

**Issue by lejard-h** [Jaguar-dart/jaguar_serializer#47]
In Order to be able to serialize and deserialize `Map<String, dynamic>`, `Map`, `List<dynamic>`, `List`

We could introduce `@RawMap` and `@RawList` annotations to tell to the serializer to directly use the result of `JSON.decode`

```dart
@GenSerializer()
@RawMap(#map)
@RawList(#list)
class ModelSerializer extends Serializer<Model> {
  ...
}

class Model {
  Map<String, dynamic> map;
  List list;
}
```

**Comment by tejainece** [comment]
We can probably implement it using `CustomFieldProcessor`?

https://github.com/Jaguar-dart/jaguar_serializer/blob/36ad88e9d9cbda62330c1392e8a2a26110ddbbf0/lib/src/serializer/custom_codec.dart
