### ISSUE TITLE
Introduce a builtin copy/clone feature

### ISSUE THREAD

**Issue by lejard-h** [Jaguar-dart/jaguar_serializer#52]
We could easily clone/copy an object using serialization then deserialization

**Comment by tejainece** [comment]
Global function called

```dart
T clone<T>(T cloned, Serializer<T> serializer) => serializer.fromMap(serializer.toMap(cloned));
```

Is this enough?

**Comment by lejard-h** [comment]
could also be on the Serializer class

```
ModelType clone(ModelType object) => fromMap(toMap(object));
```

At the end it is a 1 line change and we are not breaking anything
