### ISSUE TITLE
Separate annotations from builders

### ISSUE THREAD

**Issue by thosakwe** [Jaguar-dart/jaguar_serializer#54]
Having both the annotations *and* the `build_runner` and `source_gen` dependencies renders this package unusable in many situations.

I was trying to install the `gitter` library as a dependency in a project, and it depends on `jaguar_serializer`. However, I have other builds in my project, which require `source_gen >= 0.6.0`. As you can imagine, `pub get` fails.

The most common solution to this is to split into two packages, for example:
* `built_value` and `built_value_generator`
* `angel_orm` and `angel_orm_generator`

**Comment by lejard-h** [comment]
plan for 0.4.0, note that `gitter` package is now working without jaguar_serializer
