### ISSUE TITLE
Build serializers

### ISSUE THREAD

**Issue by tejainece** [Jaguar-dart/jaguar_serializer#56]
Right now, we cannot generate serializers for such classes:

```
/// Model for Book
class Book {
  /// Id of the book
  final String id;

  /// Name of the book
  final String name;

  /// Authors of the book
  final String author;

  Book.make({this.id, this.name, this.author});
}
```

Do we need special serializers for this? Maybe we call it `@GenBuiltSerializer()`?

**Comment by lejard-h** [comment]
probably the same as https://github.com/Jaguar-dart/jaguar_serializer/issues/1
