### ISSUE TITLE
right now jaguar_serializer depends on some non compliant ddc dependancy

### ISSUE THREAD

**Issue by Kleak** [Jaguar-dart/jaguar_serializer#62]

**Comment by lejard-h** [comment]
Do you have a list ? or a way to list them ?

**Comment by Kleak** [comment]
- yamlicious use quiver_iterable and quiver_iterable is not ddc compliant.
- intl < 0.15 is not ddc compliant

**Comment by lejard-h** [comment]
I create the pull request, I reorganised the lib folder and update intl.

We probably need to fork and fix yamlicious

**Comment by lejard-h** [comment]
It seems to work correctly, @Kleak can you test with the changes I made on the `ddc` branch ?

**Comment by Kleak** [comment]
seems to work 👍
