### ISSUE TITLE
Can yaml be stripped out to serializer_yaml?

### ISSUE THREAD

**Issue by tejainece** [Jaguar-dart/jaguar_serializer#85]

**Comment by lejard-h** [comment]
if we follow the logic we would have

- jaguar_serializer
- jaguar_serializer_cli
- jaguar_serializer_json
- jaguar_serializer_yaml

**Comment by tejainece** [comment]
Json can stay inside. Problem with yaml is brings in two depenedencies yaml and yamalicious.
