### ISSUE TITLE
DynamicTypeImpl / InterfaceType issue

### ISSUE THREAD

**Issue by CrazyStaff** [Jaguar-dart/jaguar_serializer#95]
Through the update to dart 2 the jaguar serializer causes problems.

My settings are:

Flutter Channel beta, v0.2.8
Dart 2.0.0-dev.43.0.flutter-52afcba357

**pubspec.yaml**

dependencies:
  analyzer: "^0.31.2-alpha.1" ## i also tried to get the newest version
  intl: "^0.15.4"
  http: "^0.11.3+16"
  great_circle_distance: "^1.0.1"
  ####jaguar_serializer: "^1.0.0-dev5"
  jaguar_serializer: ^1.0.0-dev1

dev_dependencies:
  build_runner: ^0.8.0
  jaguar_serializer_cli: ^1.0.0-dev1

This is the error message i got. It seems something with the analyzer package has changed..

**DynamicTypeImpl** is from package:analyzer/**src/dart**/element/type.dart

**InterfaceType** is from package:analyzer/**dart**/element/type.dart

`[SEVERE] jaguar_serializer_cli on lib/foundation/dart/logic/raw/RawType.dart:
    Error running JaguarSerializerGenerator for nalisa_foundation|lib/foundation/dart/logic/raw/RawType.dart.
    type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType' in type cast where
      DynamicTypeImpl is from package:analyzer/src/dart/element/type.dart
      InterfaceType is from package:analyzer/dart/element/type.dart`

    `[SEVERE] jaguar_serializer_cli on lib/foundation/dart/logic/Status.dart:
    Error running JaguarSerializerGenerator for nalisa_foundation|lib/foundation/dart/logic/Status.dart.
    type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType' in type cast where
      DynamicTypeImpl is from package:analyzer/src/dart/element/type.dart
      InterfaceType is from package:analyzer/dart/element/type.dart`

**Comment by lejard-h** [comment]
Hi, is it possible to share the code that is causing the issue ?

From what I can see, it is probably a dynamic field that was ignore before

**Comment by CrazyStaff** [comment]
Here are some parts. I have sent you the complete code to your email.

library de.nalisa.models.status;
import 'package:jaguar_serializer/jaguar_serializer.dart';
import 'package:nalisa_foundation/foundation/dart/communication/validator/Validate.dart';
import 'package:redstone_mapper/mapper.dart';
part 'Status.g.dart';

class Status extends Validate {
  static final SUCCESS = new Status._("success");
  static final FAILED = new Status._("failed");

  static get values => [SUCCESS, FAILED];

  @Field()
  @NotEmpty()
  String value;

  bool operator ==(o) => o is Status && o.value == value;

  Status(); // empty constructor is needed for decoding!
  Status._(this.value);


  @override
  List<Validate> getNonPrimitiveTypes() => [];

  @override
  bool isLogicValidate() {
    for(Status clientEnum in Status.values) {
      if(this.value == clientEnum.value) {
        return true;
      }
    }
    return false;
  }
}

@GenSerializer()
class StatusJsonSerializer extends Serializer<Status> with _$StatusJsonSerializer {
  Status createModel() => new Status();
}

library de.nalisa.models.priceperformance;
import 'package:jaguar_serializer/jaguar_serializer.dart';
import 'package:jaguar_serializer/jaguar_serializer.dart';
import 'package:nalisa_foundation/foundation/dart/communication/validator/Validate.dart';
import 'package:redstone_mapper/mapper.dart';
part 'PricePerformance.g.dart';

class PricePerformance extends Validate {
  static final CHEAP = new PricePerformance._("cheap");
  static final NORMAL = new PricePerformance._("normal");
  static final EXPENSIVE = new PricePerformance._("expensive");

  static get values => [CHEAP, NORMAL, EXPENSIVE];

  @Field()
  @NotEmpty()
  String value;

  PricePerformance(); // empty constructor is needed for decoding!
  PricePerformance._(this.value);

  @override
  List<Validate> getNonPrimitiveTypes() => [];

  bool operator ==(o) => o is PricePerformance && o.value == value;

  @override
  bool isLogicValidate() {
    for(PricePerformance clientEnum in PricePerformance.values) {
      if(this.value == clientEnum.value) {
        return true;
      }
    }
    return false;
  }
}

@GenSerializer()
class PricePerformanceJsonSerializer extends Serializer<PricePerformance> with _$PricePerformanceJsonSerializer {
  PricePerformance createModel() => new PricePerformance();
}

**Comment by lejard-h** [comment]
can you try to use the dependencies directly from github

```
jaguar_serializer_cli:
    git:
      url: https://github.com/Jaguar-dart/jaguar_serializer.git
      path: jaguar_serializer_cli
```

**Comment by CrazyStaff** [comment]
I tried this but then 'pub get' shows the following error:
Error on line 1, column 1: Missing the required "name" field.

`name: nalisa_foundation
description: An absolute bare-bones foundation app.
version: 0.0.1

dependencies:
  jaguar_serializer_cli:
    git:
      url: https://github.com/Jaguar-dart/jaguar_serializer.git
      path: jaguar_serializer_cli
  intl: "^0.15.4"
  http: "^0.11.3+16"
  great_circle_distance: "^1.0.1"
  redstone_mapper_mongo:
       path: ../redstone_mapper_mongo`

**Comment by lejard-h** [comment]
Il will try to release the master branch today

**Comment by CrazyStaff** [comment]
Do you think this release for the master branch will solve this issue?

**Comment by lejard-h** [comment]
Please do a pub upgrade,

let me know if you still have the issue

**Comment by CrazyStaff** [comment]
Yeah you were right. It fixed the most of the issues.

Only classes with generics doesnt work.

```
library de.nalisa.models.DataResponse;
part 'DataResponse.g.dart';

class DataResponse<T extends KeyToData> {
  DataResponse(); // needed for encode & decode

  @Field()
  @NotEmpty()
  List<T> allData = new List<T>();

  Type getSingleType() => T;
}

@GenSerializer(
    fields: const {
      'allData': const EnDecode(processor: const DataResponseProcessor())
    }
)
class DataResponseJsonSerializer extends Serializer<DataResponse> with _$DataResponseJsonSerializer {
  DataResponse createModel() => new DataResponse();
}
```

**Comment by CrazyStaff** [comment]
![jaguar](https://user-images.githubusercontent.com/26465649/38664214-3c075cb8-3e39-11e8-8d1e-486ef16d4e9a.png)
Could you also try to fix this generated generic issue? I think  a  lot of people who are using the jaguar serializer use generics somehow also.  With dart 1 everything worked quite well .

**Comment by CrazyStaff** [comment]
I have fixed this last problem on my own. I also had to change the generated file as it is shown in the following source code.
Currently, I write a bachelor thesis about flutter and also about the jaguar serializer so I had to fix it ;) so that my bachelor thesis wouldn't be in danger. Hopefully you guys find a great permanent solution.

The problem was that the following expressions didnt work for `List<KeyToData>`
**fields: const {
      'allData': const EnDecode(processor: const DataResponseProcessor())
    }** 

```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of de.nalisa.models.DataResponse;

// **************************************************************************
// Generator: JaguarSerializerGenerator
// **************************************************************************

abstract class _$DataResponseJsonSerializer
    implements Serializer<DataResponse> {
  final _dataResponseProcessor = const DataResponseProcessor();

  @override
  Map<String, dynamic> toMap(DataResponse model,
      {bool withType: false, String typeKey}) {
    Map<String, dynamic> ret;
    if (model != null) {
      ret = <String, dynamic>{};

      ret.putIfAbsent('allData', () => _dataResponseProcessor.serialize(model.allData));
      setTypeKeyValue(typeKey, modelString(), withType, ret);
    }
    return ret;
  }

  @override
  DataResponse fromMap(Map<String, dynamic> map, {DataResponse model}) {
    if (map == null) {
      return null;
    }
    final obj = model ?? new DataResponse();

    obj.allData = _dataResponseProcessor.deserialize(map['allData']);
    return obj;
  }

  @override
  String modelString() => 'DataResponse';
}
```

```
library de.nalisa.models.DataResponse;
// ...
part 'DataResponse.g.dart';

class DataResponse {
  DataResponse(); 

  @Field()
  @NotEmpty()
  List<KeyToData> allData = new List<KeyToData>();
}

@GenSerializer(
    fields: const {
      'allData': const EnDecode(processor: const DataResponseProcessor())
    }
)
class DataResponseJsonSerializer extends Serializer<DataResponse> with _$DataResponseJsonSerializer {
  DataResponse createModel() => new DataResponse();
}

class DataResponseProcessor implements FieldProcessor<List<KeyToData>, String> {
  const DataResponseProcessor();

  List<KeyToData> deserialize(String object) {
    List<dynamic> run = dataRepository.deserialize(object); // List<dynamic> to List<KeyToData> needed

    List<KeyToData> keys = new List<KeyToData>();
    for(dynamic item in run) {
      keys.add(item);
    }
    return keys;
  }

String serialize(List<KeyToData> allObjects) => dataRepository.serialize(allObjects);
}
```

**Comment by tejainece** [comment]
@CrazyStaff Does this fix your issue?
